export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/inicio";
export * from "@/pages/dashboard/servicio"
export * from "@/pages/componentes-inicio/tabla-servicio";
export * from "@/pages/componentes-inicio/convocatoria";
export * from "@/pages/serviciosocial/solicitudSS";
